apiVersion: equinix.cattle.io/v1alpha1
kind: Instance
metadata:
  name: instance-sample
spec:
  # Add fields here
  plan: c3.small.x86
  credentialSecret: equnix-metal
  metro: sg
  operatingSystem: "custom_ipxe"
  billingCycle: "hourly"
  ipxeScriptUrl: "https://raw.githubusercontent.com/ibrokethecloud/custom_pxe/master/shell.ipxe"
  vlanAttachments:
    bond0:
      - "100"
      - "1000"
  networkType: "hybrid-bonded"